swagger: '2.0'
info:
  version: 1.0.0
  title: Stub API
host: api.example.com
basePath: /v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /pets:
    get:
      description: find pets
      operationId: findPets
      responses:
        '200':
          description: pet response
          schema:
            type: array
            items:
              $ref: '#/definitions/Pet'
          examples:
            application/json:
              - name: 'Fluffy'
                tag: 'cat'
                id: 1
              - name: 'Lassie'
                tag: 'dog'
                id: 2
definitions:
  Pet:
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string